
project.name: "libcoap"

project.repositories:
    - libcoap

# Use github's distribution mechanism for core ASF libraries.
# This provides mirroring automatically for us.
#
repository.libcoap
    type: github
    vers: "0.0.1"
    user: adam31
    repo: libcoap